# Lab Task 6

In [2]:
import numpy as np
import math
import random

class Board:
    def __init__(self, n):
        self.n = n
        self.board = np.zeros((n, n), dtype=int)
        self.random_board()

    def random_board(self):
        # Place one queen in each column randomly
        self.board = np.zeros((self.n, self.n), dtype=int)
        for col in range(self.n):
            row = random.randint(0, self.n - 1)
            self.board[row][col] = 1

    def calculate_attacks(self):
        attacks = 0
        positions = []

        # Store queen positions
        for row in range(self.n):
            for col in range(self.n):
                if self.board[row][col] == 1:
                    positions.append((row, col))

        # Count attacking pairs
        for i in range(len(positions)):
            for j in range(i + 1, len(positions)):
                r1, c1 = positions[i]
                r2, c2 = positions[j]

                # Same row
                if r1 == r2:
                    attacks += 1

                # Same diagonal
                if abs(r1 - r2) == abs(c1 - c2):
                    attacks += 1

        return attacks


class Solver:
    def __init__(self, n):
        self.n = n
        self.board = Board(n)
        self.current_attacks = self.board.calculate_attacks()

    def hill_climbing(self):
        while True:
            best_board = self.board.board.copy()
            best_attacks = self.current_attacks

            # Generate neighbors (56 possibilities)
            for col in range(self.n):
                current_row = np.where(self.board.board[:, col] == 1)[0][0]

                for row in range(self.n):
                    if row != current_row:
                        new_board = self.board.board.copy()

                        # Move queen
                        new_board[:, col] = 0
                        new_board[row][col] = 1

                        temp = Board(self.n)
                        temp.board = new_board
                        attacks = temp.calculate_attacks()

                        if attacks < best_attacks:
                            best_attacks = attacks
                            best_board = new_board

            # Stop if no improvement
            if best_attacks >= self.current_attacks:
                break

            self.board.board = best_board
            self.current_attacks = best_attacks

        return self.board.board


# Solve the 8-Queen problem
solver = Solver(8)
solution = solver.hill_climbing()

print("Final Board:\n", solution)
print("Attacking Pairs:", solver.current_attacks)

Final Board:
 [[1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]]
Attacking Pairs: 1
